<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?python
import os.path
import webdav
import davutils
from urlparse import urlparse
import urllib
def url_to_unicode(url):
    return unicode(urllib.unquote(url), 'utf-8')
def file_sorted(real_path, files):
    def sort_by(filename):
        file_path = os.path.join(real_path,filename)
        return "%s-%s" % (not os.path.isdir(file_path), filename)
    return sorted(files, key=sort_by)
def path_only(url):
    return urlparse(url).path

?>
<html xmlns:py="http://purl.org/kid/ns#" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Index for ${url_to_unicode(real_url)}</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"/>
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <style type="text/css">
  .size {
    text-align: right;
  }
  </style>
</head>
<body>
  <div class="container">
    <element py:strip="" py:if="can_write">
    <h2>Upload a file</h2>
    <p>
    <form class="form-inline" role="form"
      action="#" method="post" enctype="multipart/form-data">
      <div class="form-group">
        <input type="file" name="file" size="50" />
      </div>
      <input type="submit" value="Upload"
          class="btn btn-default"
          onclick="document.forms[0].submit();this.disabled=true" />
    </form>
    </p>
    </element>

    <p class="message" py:if="message" py:content="message" />

    <h2>Current files</h2>
    <form action="#" method="post">
    <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Filename</th>
        <th>Last modified</th>
        <th>Size</th>
        <th>Select</th>
      </tr>
    </thead>
    <tbody>
    <tr py:if="has_parent">
        <td>
          <i class="fa fa-folder"></i>
          &ensp;
          <a href="${path_only(reqinfo.get_url(os.path.join(real_path, '..')))}">..</a>
        </td>
        <td>&nbsp;</td>
        <td class="size"></td>
        <td></td>
    </tr>
    <tr py:for="filename in file_sorted(real_path, files)">
        <?python file_path = os.path.join(real_path, filename) ?>
        <td>
          <i py:if="not os.path.isdir(file_path)" class="fa fa-file-o"></i>
          <i py:if="os.path.isdir(file_path)" class="fa fa-folder"></i>
          &ensp;
          <a href="${path_only(reqinfo.get_url(file_path))}">${filename}</a>
        </td>
        <td>${davutils.get_usertime(os.path.getmtime(file_path))}</td>
        <td class="size" py:if="not os.path.isdir(file_path)">
            ${davutils.pretty_unit(os.path.getsize(file_path), 1024, 0, '%0.2f') + 'B'}
        </td>
        <td class="size" py:if="os.path.isdir(file_path)"></td>
        <td><input type="checkbox" name="select" value="${filename}" /></td>
    </tr>
    </tbody>
    </table>
    <div class="clearfix">
      <div class="pull-left">
        <input type="submit" name="btn_remove" value="Remove selected" py:if="can_write"
            class="btn btn-default"
            onclick="return confirm('Really remove files?')"/>
        <input type="submit" name="btn_download" value="Download selected"
            class="btn btn-default"/>
      </div>
      <div class="pull-right">
        <a href="" class="btn btn-default">
          <i class="fa fa-refresh"></i>
          Refresh
        </a>
      </div>
    </div>
    </form>
    <hr />
    <p>Index listing generated by ${webdav.__program_name__} ${webdav.__version__}.</p>
  </div>
</body>
</html>
